import { Card } from '@/components/ui/Card';
import { Table, THead, TH, TBody, TR, TD } from '@/components/ui/Table';
import { EmptyState } from '@/components/ui/EmptyState';
import { SectionHeader } from '@/components/ui/SectionHeader';
import { IconHistory } from '@tabler/icons-react';
import { db } from '@/lib/db';
import { requireAppUser } from '@/lib/server/session';
import { getProjectContext } from '@/lib/server/context';
import { dateTime } from '@/lib/format';

export const dynamic = 'force-dynamic';

export default async function AuditTrailPage() {
  await requireAppUser();
  const { tenantId } = await getProjectContext();

  const events = await db.audit_events.findMany({
    where: { tenant_id: tenantId },
    orderBy: { occurred_at: 'desc' },
    take: 200,
    include: {
      app_users: { select: { display_name: true } },
      projects: { select: { project_code: true } },
    },
  });

  return (
    <div className="flex flex-col gap-5">
      <SectionHeader title="Audit Trail" />
      <Card icon={<IconHistory size={18} />}>
        {events.length === 0 ? (
          <EmptyState title="No audit events" message="Immutable audit trail entries generated by DB triggers appear here." />
        ) : (
          <Table>
            <THead><TH>When</TH><TH>Actor</TH><TH>Action</TH><TH>Entity</TH><TH>Project</TH><TH>Request</TH></THead>
            <TBody>
              {events.map((e) => (
                <TR key={e.id} className="hover:bg-ecms-elevated/40">
                  <TD className="whitespace-nowrap text-ecms-muted">{dateTime(e.occurred_at)}</TD>
                  <TD className="font-medium">{e.app_users?.display_name ?? 'system'}</TD>
                  <TD><span className="font-medium text-ecms-amber">{e.action}</span></TD>
                  <TD className="text-ecms-muted">{e.entity_type}</TD>
                  <TD>{e.projects?.project_code ?? '—'}</TD>
                  <TD className="text-xs text-ecms-muted">{e.request_id ? e.request_id.slice(0, 8) : '—'}</TD>
                </TR>
              ))}
            </TBody>
          </Table>
        )}
      </Card>
    </div>
  );
}
